[package]
name = "necko3-core"
version = "1.0.17"
edition = "2024"

[dependencies]
tokio = { version = "1.50", features = ["full"] }
anyhow = "1"
tracing = "0.1"

url = "2.5"

alloy = { version = "1.8", features = ["full"] }
coins-bip32 = "0.13"

serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
dashmap = "6.1"
uuid = { version = "1.23", features = ["v4"] }

sqlx = { version = "0.8", features = [
    "runtime-tokio", "tls-rustls", "postgres", "uuid", "chrono", "bigdecimal"] }

strum = { version = "0.28", features = ["derive"] }

reqwest = { version = "0.13", features = ["json"] }
serde_json = "1"
hmac = "0.13"
sha2 = "0.11"
hex = "0.4"

[dev-dependencies]
wiremock = "0.6"
criterion = "0.8.2"
proptest = "1.11.0"

[[bench]]
name = "gateway"
path = "benches/gateway.rs"
harness = false