[package]
name = "necko3-types"
version = "0.1.4"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
strum = { version = "0.28", features = ["derive"] }

uuid = { version = "1.23", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

alloy-primitives = { version = "1.6", features = ["serde"] }