[package]
name = "necko3-database"
description = "Database traits (`DatabaseStore`, `DatabaseExt`), implementations (`PostgresAdapter`, `InMemoryAdapter`), and decorators (`CachedDb`, `NotifyingDb`)."
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true

async-trait = "0.1"
sqlx = { version = "0.9", features = [
    "runtime-tokio", "tls-rustls", "postgres", "uuid", "chrono", "bigdecimal"] }

dashmap = "6.2"
arc-swap = "1.9"
parking_lot = "0.12"

chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.23", features = ["v4", "serde"] }

serde.workspace = true
serde_json = "1"

alloy-primitives = { version = "1", features = ["std", "serde"] }

necko3-types.workspace = true