ALTER TABLE chains ALTER COLUMN watch_addresses TYPE VARCHAR(128)[];

ALTER TABLE tokens ALTER COLUMN contract_address TYPE VARCHAR(128);

ALTER TABLE invoices ALTER COLUMN address TYPE VARCHAR(128);

ALTER TABLE payments ALTER COLUMN tx_hash TYPE VARCHAR(128);
ALTER TABLE payments ALTER COLUMN "from" TYPE VARCHAR(128);
ALTER TABLE payments ALTER COLUMN "to" TYPE VARCHAR(128);
