[package]
name = "necko3-blockchain"
version = "0.1.7"
edition = "2024"

[dependencies]
tokio.workspace = true
tracing.workspace = true

coins-bip32 = "0.13"
alloy = { version = "2.1.0", features = ["full", "reqwest-rustls-tls", "rpc", "json-rpc"] }

tower = "0.5"
reqwest = "0.13.4"

async-trait = "0.1"
anyhow = "1"
url = "2.5"

necko3-types = { path = "../necko3-types" }
